### ISSUE TITLE
DaVinci's Vessels crash when mounting ship

### ISSUE THREAD

**Issue by dementedkaneki** [adam9899/Issues#101]
Whenever I mount my assembled vessel it crashes. It tells me a potential cause is either Moving World, DaVinci's Vessels, Reskillable, Farseek.

**Comment by ByteTemplar** [comment]
DaVinci's Vessels mod is extremely unstable tbh, imo it should be removed, cause it will cause lotsa problems for people playing the modpack, cause its early way to fly...

If you really wanna use it, use the buffer block, when building so you dont accidently try assemble more than wanted block. Try using only vanilla blocks, most modded blocks will cause problems and crash the game!

**Comment by dementedkaneki** [comment]
Thanks I got it working well now!
