### ISSUE TITLE
Startup crash twice in a row

### ISSUE THREAD

**Issue by Reioflight** [adam9899/Issues#103]
![Minecraft 1 12 2 2020-01-11 1_59_43 PM](https://user-images.githubusercontent.com/59775570/72209362-4450f700-347b-11ea-8d30-550e9fc8c5b2.png)
So far has crashed twice from an unknown problem. Downloaded from the Twitch launcher. https://paste.dimdev.org/qogicojazi.mccrash
How should I fix this?

**Comment by ByteTemplar** [comment]
java.lang.OutOfMemoryError

Give it more RAM, that 3Gb wont be enough, that you have given it...
5.5Gb is minimum, but to it run decently I recommend giving 8Gb as it says so in the modpack page even.

**Comment by Reioflight** [comment]
How do I do that? I am new to modpacks and don't want to mess my computer up.

**Comment by ByteTemplar** [comment]
https://help.twitch.tv/s/article/How-to-Play-Minecraft-with-Twitch-App?language=en_US#Settings

Java Settings:
- Maximum Memory Allocation - allows you to allocate how much memory for your game.

**Remember** to take into account, how much RAM your computer has!

**Comment by Reioflight** [comment]
Thank you so much!
