### ISSUE TITLE
no monster spawns in server

### ISSUE THREAD

**Issue by Fornax42** [adam9899/Issues#107]
As the title says, me and a friend can't get monster to spawn; both normal, through spawn eggs or the summon command. in the server properties spawn-monsters = true and difficulty = 2, so that shouldn't be the problem.
when we spawn some zombies for instance with a spawn egg, we do hear their cry, but there's nothing to see or anything. please help, because we have no idea what it could be

**Comment by zaekeon** [comment]
i had the same problem and it seemed to be around either spawn protection in the ftbutil config or maybe something with claimed chunks...right now i'm fighting an issue where auto placers and stuff don't work in claimed chunks regardless of config.

**Comment by Fornax42** [comment]
I got it resolved with help in the Discord server. It was indeed a thing with the spawn protection in the ftbutil config for me. Switching it to false fixed it for me
