### ISSUE TITLE
[1.3] - Vampirism - Cannot feed

### ISSUE THREAD

**Issue by majora2007** [adam9899/Issues#138]
Users are reporting that they cannot feed after being turned into a Vampire. Keybindings have been changed to unique keys, but are unable to feed on anything.

PVP is off on the server and it is a fresh install of 1.3.

**Comment by preceptor-teeth** [comment]
When you see the vamp fangs icon on the screen, you have to hold down the feed key.  Just pressing it once won't work.

**Comment by majora2007** [comment]
Seems it works on 1.3.2. Thanks for help, will close.
