### ISSUE TITLE
Thermal Expansion machines not receiving power from Energy Conduits

### ISSUE THREAD

**Issue by Sambo3975** [adam9899/Issues#144]
For some reason, the Thermal Expansion machines won't receive RF from EnderIO Energy Conduits, or any equivalent from the other mods. The conduits hook up to the machines, but no RF is transferred.

**Comment by ByteTemplar** [comment]
I have long line of energy conduits and on that have Thermal Expansion, NuclearCraft and EnderIO machines, all working without any problems.

Are you sure there is power going to conduits, have you tried putting other machines on them?

**Comment by H4nSolo** [comment]
Right Configurations? 
Input.... Output?

**Comment by Sambo3975** [comment]
Everything works fine. I just forgot to set my powercell to output. I'll go ahead and just close this now.
