### ISSUE TITLE
Sewage Bucket In Transmutation Tablet Causes Game Crash

### ISSUE THREAD

**Issue by ghost** [adam9899/Issues#149]
Steps to reproduce:
1. Learn the sewage bucket from Industrial Foregoing in ProjectE's transmutation tablet (I am using the portable one if that helps).
2. Hover over the learned item (you'll notice it appears as an empty bucket).
3. Watch as the game instantly crashes (thanks to VanillaFix, only to the main menu).

Note: VanillaFix suggests that this crash is potentially a result of Stupid Things, Farseek and ProjectE. Seems like an odd combination, but may be worth looking into.

Let me know if you need any more info!

**Comment by Coji4000** [comment]
ProjectE is not a part of this modpack

**Comment by ghost** [comment]
Oh my gosh, my apologies I thought it was. Embarrassing mistake!

I had added a few of my own favourite mods into the mix, but I didn't think ProjectE was one of them. Bad memory!

Sorry for any trouble! <3
