### ISSUE TITLE
Biomes O plenty server world type fix

### ISSUE THREAD

**Issue by jinkhya** [adam9899/Issues#156]
Hello,
So i noticed like a few other people that even though the server.properties said BIOMESOP, the server was not generating any of the bop biomes. 

It is because there's a space at the end of level-type=BIOMESOP that needs to be deleted.

Best regards :)
Jin

**Comment by adam9899** [comment]
Thanks for letting me know!
Wow what a silly mistake :D 

Fixed in 1.3.2

**Comment by jinkhya** [comment]
no problem :) thank you for making the pack !
