### ISSUE TITLE
Fixed configs to allow Bewitchment's salt to stop turning into Mekanism's

### ISSUE THREAD

**Issue by katubug** [adam9899/Issues#171]
Related issues: 
https://github.com/adam9899/Issues/issues/116
https://github.com/adam9899/Issues/issues/73
https://github.com/adam9899/Issues/issues/35

I checked the UniDict config and noticed that the changes attempting to blacklist Bewitchment's salt were outside of the angle brackets, and thus weren't getting read correctly. Additionally, one just said "salt" instead of the full ID of the salt items. I went ahead and edited the config to properly blacklist Bewitchment's salt from turning into Mekanism's. Additionally, I also added an entry for salt items in the InstantUnify config. It should be redundant, but I figured it can't hurt! lol

Here are the files:

[MCEternalSaltConfigFix.zip](https://github.com/adam9899/Issues/files/4141835/MCEternalSaltConfigFix.zip)

Just a note - behavior with these files is reversed, where Mekanism's salt dust will turn into Bewitchment's. However, I checked, and all of Mekanism's recipes use the salt oreDict, so they can use Bewitchment's salt in them. The only exception is the Mekanism salt block recipe, but since the salt block isn't used in any other recipes, that shouldn't be an issue.

**Comment by Matteo961** [comment]
> Related issues:
> #116
> #73
> #35
> 
> I checked the UniDict config and noticed that the changes attempting to blacklist Bewitchment's salt were outside of the angle brackets, and thus weren't getting read correctly. Additionally, one just said "salt" instead of the full ID of the salt items. I went ahead and edited the config to properly blacklist Bewitchment's salt from turning into Mekanism's. Additionally, I also added an entry for salt items in the InstantUnify config. It should be redundant, but I figured it can't hurt! lol
> 
> Here are the files:
> 
> [MCEternalSaltConfigFix.zip](https://github.com/adam9899/Issues/files/4141835/MCEternalSaltConfigFix.zip)
> 
> Just a note - behavior with these files is reversed, where Mekanism's salt dust will turn into Bewitchment's. However, I checked, and all of Mekanism's recipes use the salt oreDict, so they can use Bewitchment's salt in them. The only exception is the Mekanism salt block recipe, but since the salt block isn't used in any other recipes, that shouldn't be an issue.

Thx helped us out bigtime :)

**Comment by adam9899** [comment]
Thanks! Fixed for the next version.
