### ISSUE TITLE
Can't do the ''a firey projectile'' thaumcraft task

### ISSUE THREAD

**Issue by KajuzKajus** [adam9899/Issues#179]
I am a vampire hunter, can this affect the game so the thaumcraft task to get hit by a fireball not work?

**Comment by ByteTemplar** [comment]
If other mod somehow modifies some scripted triggers, it might affect the outcome. So its possibe, and pretty damn hard to foresee when making quests.

So this needs more testing from people...

**Comment by KajuzKajus** [comment]
I see, do you maybe know a command, that would let me complete the firey projectile task then?

**Comment by ByteTemplar** [comment]
I dont have much knowledge on FTBQuests mod and the Wiki is quite light on information. All I found is to get in edit mode, there is command "/ftbquests editing_mode", after that you are on your own. **Make sure to have backups, before starting to mess with these!**

https://github.com/FTBTeam/FTB-Quests/wiki/For-Modpack-Creators

_Right-click on any chapter, quest, task or reward to open context menu from where you can edit objects, delete, move, etc._

**Comment by KajuzKajus** [comment]
> I dont have much knowledge on FTBQuests mod and the Wiki is quite light on information. All I found is to get in edit mode, there is command "/ftbquests editing_mode", after that you are on your own. **Make sure to have backups, before starting to mess with these!**
> 
> https://github.com/FTBTeam/FTB-Quests/wiki/For-Modpack-Creators
> 
> _Right-click on any chapter, quest, task or reward to open context menu from where you can edit objects, delete, move, etc._
Thanks dude, much appreciated

**Comment by blairwilson** [comment]
change in `config/ebwizardry/ebwizardry.cfg`
`B:replaceVanillaFireballs=true`
to
`B:replaceVanillaFireballs=false`
