### ISSUE TITLE
[1.3.2] Auto-Jump Re-inabling randomly

### ISSUE THREAD

**Issue by majora2007** [adam9899/Issues#183]
Steps to reproduce:
1. Login
2. Turn off auto-jump
3. Die

It is random for the most part, but if I recall, dieing generally turns it on. I have confirmed with other users on the discord this affects them along with all users on my server.

**Comment by ByteTemplar** [comment]
Or do you accidentally press the keybind to activate it? Quark has it and is by default B, that is used for other things too...

**Comment by majora2007** [comment]
I don't think I am, but I will double check when I get home tonight.

**Comment by majora2007** [comment]
Finally got to test this. It was me pressing B to bookmark and thus re-enabling it. Thanks.
