### ISSUE TITLE
Bolt core stencil option missing

### ISSUE THREAD

**Issue by BarathisGit** [adam9899/Issues#202]
There is no option in the Stencil table to select the Bolt core so a Bolt core cannot be created.  If this is by design, I'd think that you should also remove the crossbow and parts.

**Comment by WhitePhant0m** [comment]
You make the bolt core by putting an arrow shaft on a casting table and pouring molten metal (i think any will do) on it, after waiting a bit it will turn into a bolt core. Bolt core never had a stencil.

**Comment by BarathisGit** [comment]
No, then you couldn't use it to craft thing such as wooden or gem types of bolt cores.

**Comment by WhitePhant0m** [comment]
> To make a bolt core, place an Arrow Shaft, of any type, into a casting table, and pour any molten metal over it. The metal will form the tip of the bolt core and the arrow shaft will become the main material.

I took this straight from the wiki.
Also, it tells you how to make a bolt core in the book in-game

**Comment by Glendening** [comment]
Aleksi is correct. You pour metal over an arrow shaft. Before arrow shafts existed you poured metal over a tool rod. This is how it has always been done in TiC
This is not a bug and should be closed.
