### ISSUE TITLE
RFTools builder won't mine blocks

### ISSUE THREAD

**Issue by Avalonzo** [adam9899/Issues#204]
Basically I'm trying to use the builder from RFTools with a quarry card it has a chest, lever and power but won't mine is there some sort of config setting in this pack that prevents builder quarrying in the Overworld?

![2020-02-12_21 09 29](https://user-images.githubusercontent.com/8142543/74377903-c61aa400-4ddc-11ea-8339-729a6bcf9843.png)

![2020-02-12_21 10 03](https://user-images.githubusercontent.com/8142543/74377916-cc108500-4ddc-11ea-8211-ee230e510902.png)

![2020-02-12_21 10 07](https://user-images.githubusercontent.com/8142543/74377928-d0d53900-4ddc-11ea-8aad-8924aa557ae5.png)

**Comment by Avalonzo** [comment]
I did a bit more testing and seems to be related to the minecolonies boundary area.

**Comment by ByteTemplar** [comment]
There was similar issue with Digi Miner and I posted instructions, how to disable MineColonies protection there. Never got report back if it works and has any further issues though. Make backups first before trying!

https://github.com/adam9899/Issues/issues/159#issuecomment-580535640

**Comment by Avalonzo** [comment]
I can confirm your instructions work perfectly and thank you so much.
