### ISSUE TITLE
Keep crashing on a friend's server.

### ISSUE THREAD

**Issue by Eli-Liz** [adam9899/Issues#208]
I keep crashing randomly every 30 minutes. I had my friend remove the dank null mod from the server because that's what the crash reports says was causing my crash. After I removed that mod, I'm now crashing every 30 minutes to a different mod. Starting to think there's a different reason I'm crashing because no one else in the server is crashing to mods except me. 

Here's the 1st crash report - https://pastebin.com/uaVHsyii
Here's the crash report I got after I got my friend to remove the dank null mod from the server - https://pastebin.com/BLq9FrCT

**Comment by Glendening** [comment]
Gonna suggest using a newer version of java then 1.8.0_51 as a first step to troubleshooting this.
The current version is 1.8.0_241
Make sure your launcher (twitch or MultiMC) is pointing to the right java install.
