### ISSUE TITLE
Launching Crash with plenty of RAM

### ISSUE THREAD

**Issue by Drakonisx** [adam9899/Issues#210]
I played for about 4 hours last night then this morning no matter how much I set the RAM (most I set was ~10gb) to it crashes as forge is loading. If anyone can help that would be greatly appreciated was really enjoying this and idk how to fix it. 
[hs_err_pid14064.log](https://github.com/adam9899/Issues/files/4206607/hs_err_pid14064.log)

**Comment by ByteTemplar** [comment]
First, try updating you Java:
https://www.oracle.com/java/technologies/javase-jre8-downloads.html

You are using ancient one (51-b16) latest version is 241...

**Comment by Drakonisx** [comment]
Okay yeah my windows had updated and was messing it up. I did that and restarted my pc and it's working now, ty.
