### ISSUE TITLE
Sudden not responding

### ISSUE THREAD

**Issue by LuisSolanoVillalaz** [adam9899/Issues#212]
When playing the game normally the game freezes suddenly and then windows closes it for not responding. this happens every time after 10-30 min after i load up the world. it is not a ram problem, i gave it 7gb of ram and when i open f3 it is about 60%-80% and i have no fsp problems. 
Here is the latest crash log.
[crash-2020-01-04_11.41.47-client.txt](https://github.com/adam9899/Issues/files/4207538/crash-2020-01-04_11.41.47-client.txt)

On a side note: when i load up the world in the overworld it takes a while but when i enter the nether or the twilight forest they instantly load, making me think that they load both load when i load the world, not mater from where.

**Comment by ByteTemplar** [comment]
Does your computer have 8GB memory total perhaps? Should list specs when reporting problems...

**Comment by LuisSolanoVillalaz** [comment]
Sorry, yes it has 8 GB of RAM y tried to allocate 6GB that was the recommended amount but still freeze crash and i am not talking about the lag you get from low ram. when playing i am playing with no lag no stutter then suddenly the game does not respond.

**Comment by ByteTemplar** [comment]
That sounds like, that the computer is totally running out of memory and starts crashing things. This is huge pack and trying to run it on 8Gb memory is asking for trouble. 

There really is no issue here other than your computer cant handle the modpack, unfortunately...
And still you didnt list any other specs either. By looking the log files, I assume its a laptop with integrated Intel graphics on top of all (it probably allocates part of memory too, so you might even not have full 8Gb available for system).

**Comment by LuisSolanoVillalaz** [comment]
well sorry i didn't give my full specs, i thought it wasn't necessary, it is a pc that  i build recently and my specs are:
Asus Tuf b365-plus gaming motherboard
Intel Core i5-9400 cpu 2.90GHz CPU
Nvidia Geforce GTX 1050 Gafic GPU

**Comment by ByteTemplar** [comment]
That 8Gb memory is your main problem to run bigger packs, there just isnt any fix for it, other than upgrading to 16Gb.

All 1.12 packs are much more RAM hungry...

**Comment by LuisSolanoVillalaz** [comment]
ok thanks
