### ISSUE TITLE
Levelup Reloaded perks not working in Multiplayer for some

### ISSUE THREAD

**Issue by ImAkemi** [adam9899/Issues#231]
On a friend's server I am unable to get the benefits of levelup reloaded perks (ore doubling, more efficient furnaces, faster furnace cooking time, or anything) while my friend who is running the server is able to.

I'm not sure if this is an issue with the mod, or the mod pack itself. My friend is able to get doubled ore and any other perk benefits, we are both OP'd and I'm not sure why it wouldn't work for me.

EDIT: after deleting my player data from the server and logging back in, I was able to use the perks again

EDIT 2: Was able to re-obtain old player data from a backup which should also be broken in, we updated the server but mine was the only one broken since I can remember. Not sure when it stopped working (if it worked ever). I have attached it in the events it can help. The only thing I can think of that broke it was that I became a vampire and then reverted after leveling up vampire skills for a bit.
[akemi_playerdata.zip](https://github.com/adam9899/Issues/files/4238450/akemi_playerdata.zip)

**Comment by ByteTemplar** [comment]
Just as a notice, there is also keybind to enable/disable the perks, so is it possible you perhaps misclicked it?

**Comment by ImAkemi** [comment]
Hmm, that's probably it. Maybe if that mod had any type of detailed description on it's mod page that talked about this I could have checked, instead of thinking that I could somehow disable it with a keybind and then go search through my control settings.
