### ISSUE TITLE
"He protec, He attac and most Im 100%" Text chat on the right side of the screen

### ISSUE THREAD

**Issue by Danrith** [adam9899/Issues#232]
I have been trying to remove this text on the right of the screen under the map. I couldn't figure out whether its a vanilla thing or what. It seems it's not the "Title/Subtitle Command". I'm remembered seeing the text after claiming the Turtle Mine in on the quest book seeing it has a similar flavor text. But I'm not sure after looking up the Stupid Things Mod from which the Turtle Mine originated. I need help with this. Kinda ruining the gameplay when there's a text screen on your face all the time.

**Comment by ByteTemplar** [comment]
Open the Quest book, search the quest with title of that and open it, click the pin icon in one of the upper corners of that popped window.


You have pinned the quest and thus tracking it...

**Comment by Danrith** [comment]
Thank you very much! I may have pinned it during a frantic clicking while doing the quest chain.
