### ISSUE TITLE
Forestry- Hill Cherry Tree  Overpowered

### ISSUE THREAD

**Issue by Mrroot3r** [adam9899/Issues#254]
Not usually one to complain about OP things in SP games, but these trees just drop too many cherries. They are not to OP by themselves, but each tree drops almost a stack. Combine these with recipes like Cherry Juice(2 cherries) and Cherry Smoothie (2 cherries and a snowball) and they become by far the most powerful food i've seen so far. They are easy to create, and the ability to eat them at any time as they act like potions is insane. 

Smoothies heal like 3 saturation and 2.5 hunger iirc, and can be eaten at any time with fast animation. Think they are good? Smoothies also give 30 seconds of speed buff guaranteed, and the juice has a medium chance to grant speed.

I'm not saying the recipe should be removed or anything, but i think adjusting the drop rate of the cherries might be a good idea. It's hard to not want to only use these now as all of the other foods are so hard to make.

Thank you for taking the time to consider this, I really want to see this modpack continue to succeed. Im only 12 hrs in but its on its way to being my favorite of all time!

**Comment by ByteTemplar** [comment]
Make Sandwich station and you can make amazing food with anything added to the bread (even other prepared foods from multiple resources), it works with baguettes (AA) or rice bread too, that is easy to make.

There are quite a few foods you can get pretty easily and are powerful, make a Chef Rat and there is "secret" food it can make that will blow your mind. Its not that hard to achieve either...

And I believe any juice can give you buffs and are extremely easy to make and farm the product.

**Comment by Mrroot3r** [comment]
Interesting, I have the sandwich station but have not mess with it yet. And i haven't been able to tame any rats yet either.

But I think my issue with the cherries were not so much the food, but really the amount you can acquire with no effort. a stack of saplings and some bonemeal, or even the time bottle and boom 64x stacks of cherries, for 32 stacks of juice or 32 stacks of smoothies because snowballs are super easy to get.

I feel like if they dropped more like 10-20 per tree instead it would seem a lot more fair, unless maybe every fruit tree drops this many? the only other fruit trees i've seen have the fruit hanging off the bottom that needs to be picked, definitely not as easy as vein mining the tree. But maybe i'm wrong, ill go check out the other fruit juices/smoothies later.

**Comment by ByteTemplar** [comment]
Apatite is easy to find in huge veins, with sand can be made to fertilizer (you get so much of it) and any crop is easy to get huge amounts of.
