### ISSUE TITLE
Crashing after playing for a few minutes

### ISSUE THREAD

**Issue by laupies** [adam9899/Issues#255]
My game is always crashing after playing for a bit. I can't find the issue. 
I also don't understand the crash report. Can someone help me?

Thanks in advance

Here's my latest crash log:
[crash-2020-03-01_14.30.44-client.txt](https://github.com/adam9899/Issues/files/4272156/crash-2020-03-01_14.30.44-client.txt)

**Comment by ByteTemplar** [comment]
First, I would recommend updating your Java version, its very old (probably using what comes with Twitch?).

https://www.oracle.com/java/technologies/javase-jre8-downloads.html

**Comment by laupies** [comment]
Thanks!! Couldn't update java for some reason, but uninstalled and installed latest version. No more problems now!
