### ISSUE TITLE
MC.Eternal Crashes on start

### ISSUE THREAD

**Issue by ghost** [adam9899/Issues#257]
Here is the Log of the Game Crash i get.
If there is more Information needed, inform me please :)
https://paste.dimdev.org/nudufukupi.sql

**Comment by ByteTemplar** [comment]
Redownload, looks like your install is corrupt:

```
Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
```

**Comment by ghost** [comment]
so. that did not fix it.
uninstalled java, minecraft, twitch app.
restarted and reinstalled Java 64xbit.
Reinstalled Minecraft. Launched Minecraft once.
Installed modpack. Launched modpack with 8GB Ram.
Same issue in the crash.log

Here is a minecraft game output window. https://paste.dimdev.org/unizojayef.cpp
And I can normally launch minecraft.
But not this or other mods (SkyFactory4)

**Comment by ByteTemplar** [comment]
Something is wrong with the files, according the report...

Try MultiMC?

**Comment by ghost** [comment]
OK.
Thank you ByteTemplar. It works!
