### ISSUE TITLE
/Dank/Null Docking Station Item Duplication

### ISSUE THREAD

**Issue by gloomyMoron** [adam9899/Issues#279]
Disable the Docking Station's recipe as it is possible to duplicate everything that is inside of a Dank/Null.

I don't know the steps, completely, to reproduce it, but this is the conversation I had with the person who noticed this earlier.

>Ilyushin IL 28 Jet BomberToday at 7:36 AM
>Uh oh /dank/null is broken like crazy

>ViridianToday at 7:36 AM
>what's wrong

>gloomyMoronToday at 7:36 AM
>I mean, I've not experienced issues with it but that doesn't mean they don't exist.
>If you're using the stand though, those things are glitchy

>Ilyushin IL 28 Jet BomberToday at 7:37 AM
>yea I break the stand after extracting the items from it to collect it then place it back down, then the items are back

>gloomyMoronToday at 7:37 AM
>Yeah. The Docking Station is super buggy. I'm surprised it is enabled.

**Comment by gloomyMoron** [comment]
https://www.youtube.com/watch?v=lGs_gL6cxnY
They made a video of the bug happening.

Modpack version is 1.3.3

**Comment by HolyMilkMan** [comment]
Updated video https://www.youtube.com/watch?v=5mjGV3Ao21k

**Comment by HolyMilkMan** [comment]
Does not work in version 1.3.4

**Comment by gloomyMoron** [comment]
The latest version fixed it. Closing this.
