### ISSUE TITLE
1.12.2 How to reset vanilla foods to normal?

### ISSUE THREAD

**Issue by RepoDraghon** [adam9899/Issues#290]
I don't see a config file to set the food back to stock...

**Comment by ByteTemplar** [comment]
In config directory, edit file named `harvestcraft.cfg`, line 181:

`# Makes changes to vanilla food item and drop hunger restore and saturation values to be balanced with HarvestCraft food. [default: true]`
`B:enablevanillafoodBalance=true`

Change it to `false`

I would just make the Sandwich station as quests suggest at start of the game, it can make very good food. You can add anything in a bread (rice bread and baguette works too).

**Comment by RepoDraghon** [comment]
Thank you
