### ISSUE TITLE
Fluxed Electrum

### ISSUE THREAD

**Issue by tristo7** [adam9899/Issues#30]
Fluxed Electrum can be created in a smeltery, but you are unable to make parts/ingots out of it.

Pack version 1.1

**Comment by adam9899** [comment]
Currently, there are materials that are uncraftable but obtainable from loot chests, the rest of the materials will be disabled in future updates.

**Comment by DreamSmith** [comment]
Still alloyable in smeltery. 22/04/2020 1.3.5.3
Complaints from server users.
