### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by clonepilotz** [adam9899/Issues#307]
Bonzai trees for tree farming ?

**Comment by burgstore** [comment]
would it be necessary? you can get wood and saplings with essence from mystical agriculture.

**Comment by clonepilotz** [comment]
It was more the idea for modded trees since trees can't really go in garden cloches and it made me think hmm a way to automate trees in a small area instead of the large farms eg multiblock farms. Just ideas of course if you decide not to all good I'll just mod it in my self 😀

**Comment by ByteTemplar** [comment]
There is Thermals way, that is imo much better, cause its not as OP as bonsai tree mod. 

https://teamcofh.com/docs/1.12/thermal-expansion/phytogenic-insolator/

Ofc anyone can add mods if they want to do so...

**Comment by clonepilotz** [comment]
Ok fair enough I just wondered thanks for ur time
