### ISSUE TITLE
RFTools Dimensions, empty dimension tab recipe broken

### ISSUE THREAD

**Issue by RoyLeviGit** [adam9899/Issues#330]
When trying to craft an empty dimension tab you get an "Advanced recipe" from "LittleTiles" mod.

**Comment by xChaosityx** [comment]
Press the right pointing arrow under the item collection on the crafting table, its a double recipe so you need to cycle thru the recipes.

**Comment by ForbiddenAedra** [comment]
This is useful when using the standard crafting table or crafting station, however the arrow when using the AE2 crafting monitor or pattern terminal(auto crafting) does not seem to alternate as the other did. Clicking the button does nothing even though it is visible.

Its not an issue I have come across before, I have never used the cycle through recipes option so this is probably issue with AE2 but would be nice for the recipe to be changed to avoid this problem.

Also when shift clicking to create multiple the cycle resets after a couple, so if your wanting to make a stack its a bit annoying.
