### ISSUE TITLE
Farming and Agriculture questline unable to be completed 

### ISSUE THREAD

**Issue by xerozero** [adam9899/Issues#371]
I have every quest in this tab completed but it still says 98%
![quest minecraft](https://user-images.githubusercontent.com/62699229/77640668-eda18680-6fae-11ea-9ebf-a093704e47cc.png)

**Comment by ByteTemplar** [comment]
Bottom line, you missing one seed...

**Comment by xerozero** [comment]
That is weird because i went over that quest tab about 6 times before taking the screenshot and that quest was ticked.
