### ISSUE TITLE
Error on launch Electroblob.

### ISSUE THREAD

**Issue by quantumicrowave** [adam9899/Issues#396]
The game works perfectly when launched but sometimes on launch it gets an error.
https://paste.dimdev.org/iwuxenuxad.mccrash

**Comment by Charismara** [comment]
This looks like an issue which is only caused by Electroblobs. Please report this bug to the mod author.

**Comment by Quinci135** [comment]
Ebwizardry version in pack is 4.2.9.
Most recent version (4.2.10) released on march 19th fixes the issue
(spanish lang file mispells "introduction" as "introduccion" and fails to load.)
https://github.com/Electroblob77/Wizardry/issues/365

**Comment by Charismara** [comment]
@adam9899 Updating Electroblob's may fix this issue.
@gonsanbo until the mod is updated you chould change your lang to english. I guess this would be an workaround 👍
