### ISSUE TITLE
Conflicting recipes Quark / Malisis Doors

### ISSUE THREAD

**Issue by TheRealWebGremlin** [adam9899/Issues#410]
Hi,

I've found a couple of conflicting recipes between the Quark and Malisis Doors mods. Specifically the following trapdoors:

Acacia
Birch
Dark Oak
Jungle
Spruce

Kind regards.

**Comment by Kyzoku** [comment]
For some reason NoMoreRecipeConflict is picking these up as conflicts.

**Comment by TheRealWebGremlin** [comment]
Seems to be resolved in 1.3.5.3. Thank you.
