### ISSUE TITLE
Hearing pig noises

### ISSUE THREAD

**Issue by arcanine537** [adam9899/Issues#412]
I am hearing pig noises at all times in the MC Eternal modpack. I saw that I had a pig nose on April 1st, and had pig noises... These noises are still continuing going on April 3rd. I don't know if you can help with this. I don't know where this help report is going, but it is the first thing that pops up when I load into MC Eternal... Sorry if this is not the right place to report this.

**Comment by 3x1at1on** [comment]
April Fools! Nothing more. Don't know which mod has done it though.

**Comment by arcanine537** [comment]
Okay. I had made a noise filter to get rid of it... Just took it out and no more noises remain. Thanks!
