### ISSUE TITLE
Repeated server crashes with ConcurrentModificationException

### ISSUE THREAD

**Issue by nimsarr** [adam9899/Issues#430]
I run my own server on my own machine allocating 15GB of ram to the server, and after a few hours of gameplay or less, it crashes with this same exception every time, without fail. Players aren't doing anything in particular whenever it happens. 

I've added some mods to the pack including Jurassicraft, Aether Legacy, Project Red, Galacticraft, and Jabelar's Moving Light Sources. 

I've also noticed a lot of warnings in the server log every so often about "Keeping entity 'name' that already exists with UUID 'id'".

Not sure if any of these things are the cause, but it's really hard to debug since the error doesn't point to any mod in particular.

[server crash - ConcurrentModificationException.txt](https://github.com/adam9899/Issues/files/4442139/server.crash.-.ConcurrentModificationException.txt)

**Comment by ByteTemplar** [comment]
You could try using:
https://www.curseforge.com/minecraft/mc-mods/deuf-duplicate-entity-uuid-fix

It seems to be a vanilla bug: https://bugs.mojang.com/browse/MC-95649

I would also remove added mods, if the problem persist, to see if those are the reason...

**Comment by Charismara** [comment]
@nimsarr If the problem is solved, please close this issue.

**Comment by nimsarr** [comment]
Deuf helped remove the warnings, but that seems to be a separate issue. The server still eventually crashed with the same exception.

The players on my server have been using most of the custom mods, so I can't just remove them. I guess I would have to test on a newly created world or make a backup, and I haven't done that yet. I'll update here when I do.

**Comment by nimsarr** [comment]
After lots of painstaking testing with different combinations of mods, the crashes seem to have been caused by Jurassicraft. It's unfortunate that I had to remove it, but at least it's not part of the actual modpack. :) Maybe it was because of Jurassicraft running alongside another mod? Hard to tell, I guess we'll probably never know.

Thanks for the help!
