### ISSUE TITLE
destroying dark druid spawner before making talisman crashes server

### ISSUE THREAD

**Issue by knightrum** [adam9899/Issues#434]
I attempted to destroy a dark druid spawner under the altar before i had previously crafted the talisman , and it caused the server to crash.

**Comment by 3x1at1on** [comment]
Same issue as Spawners in Betweenlands #426 
Update minecolonies to latest beta should resolve this issue.

**Comment by Charismara** [comment]
@knightrum This is an duplicate. Please close this issue.
