### ISSUE TITLE
Midnight mod error on server

### ISSUE THREAD

**Issue by nimsarr** [adam9899/Issues#44]
This error doesn't crash the server, but often comes up repeatedly back-to-back while the server is running.

https://pastebin.com/5WrzJhPh

**Comment by hamsterpowerftw** [comment]
Same issue, It was showing up every few seconds or so in my base.

**Comment by Freddy4258** [comment]
same, on occasion i get upwards of 12 errors occurring at once.

**Comment by adam9899** [comment]
The message can be disabled in the Vanilla fix config, there are some strange issues with rendering Midnight portals and Vanilla fix

**Comment by laserlemons** [comment]
This can be remedied by setting the rift spawn chance to 0 in the midnight config until the bug is fixed.
