### ISSUE TITLE
Cursed Earth Spawns instantly despawning

### ISSUE THREAD

**Issue by baelrath** [adam9899/Issues#452]
Trying to set up a mob farm with Crusher and Cursed Earth. The mobs spawn, but instantly despawn before they can be killed.

Only mobs that stick around long enough are Vampire ones and those Pumpkin scarecrow things and some rats.

Edit: Is Spawn protection affecting this? I've moved far away and also tried in another dimension and I think its working...

… as far as I knew I thought I disabled spawn protection in the Settings...

**Comment by ByteTemplar** [comment]
Spawn protection will mess up with cursed earth etc... mechanics spawning mobs.

You could try moving it, just make backups before trying, just in case:
https://minecraft.gamepedia.com/Commands/setworldspawn

**Comment by Kadah** [comment]
Spawn protection will cause this, it tripped me up as well.

Though if you only want to grind vampires, they ignore spawn protection for some reason.

**Comment by baelrath** [comment]
:) Moved it a away from spawn, no issues now. Certainly caused some concern until we figured that out though :()
