### ISSUE TITLE
Spontaneous crash returning from Betweenlands dim!!

### ISSUE THREAD

**Issue by oacaptain** [adam9899/Issues#456]
https://paste.dimdev.org/xezizinove.mccrash It has done it several times now. The pack starts to be unplayable and the sad thing is that I love this pack!! I hate stop playing!!! Please do something!!!

**Comment by Avalonzo** [comment]
Try updating your java as your still using a java from 2015 being so out of date bound to cause some issues.

**Comment by oacaptain** [comment]
Any chance of how to update the java in Minecraft??

George Karpoutzakis

**Comment by Avalonzo** [comment]
Java is an external program that Minecraft runs on you can update it via the Java website - https://www.java.com/en/ Hopefully this will fix it.

**Comment by oacaptain** [comment]
Thank you Avalonzo I am going to try it and if something happens I will return with a comment!!!! Much love!!

**Comment by Charismara** [comment]
@oacaptain please close this issue and reopen it if the issue still exist

**Comment by oacaptain** [comment]
The reason I didn't close it yet is this https://paste.dimdev.org/alaxanamam.mccrash new crash after updating the java to the latest version 180 241 any thoughts????

**Comment by oacaptain** [comment]
The reason I didn't close it yet is this https://paste.dimdev.org/alaxanamam.mccrash new crash after updating the java to the latest version 180 241 any thoughts????

**Comment by Avalonzo** [comment]
I'm not the greatest at reading crash logs but I do see a mention of an extra utilites 2 sound muffler. Maybe try removing the sound muffler and see if you still get the crash.

**Comment by oacaptain** [comment]
> I'm not the greatest at reading crash logs but I do see a mention of an extra utilites 2 sound muffler. Maybe try removing the sound muffler and see if you still get the crash.

I did Avalonzo this crash is after the removal of the sound mufflers

**Comment by Charismara** [comment]
> this crash is after the removal of the sound mufflers

That's weird because there are some information about a sound muffler in the crash log.
`at com.rwtema.extrautils2.blocks.BlockSoundMuffler.supressSound(BlockSoundMuffler.java:59)`

`World: (490,68,-147)`
What block is there?

**Comment by oacaptain** [comment]
> > this crash is after the removal of the sound mufflers
> 
> That's weird because there are some information about a sound muffler in the crash log.
> `at com.rwtema.extrautils2.blocks.BlockSoundMuffler.supressSound(BlockSoundMuffler.java:59)`
> 
> `World: (490,68,-147)`
> What block is there?

![2020-04-15_15 38 52](https://user-images.githubusercontent.com/34013573/79338353-d01d6800-7f2f-11ea-84b1-899aa62a42e1.png)
![2020-04-15_15 40 15](https://user-images.githubusercontent.com/34013573/79338354-d14e9500-7f2f-11ea-9715-e0137aff7a6b.png)

there is no extrautilities block there only an applied energistics cable

**Comment by oacaptain** [comment]
yet an other crash https://paste.dimdev.org/igiwafuxes.mccrash from applied energistics this time!!!

**Comment by Avalonzo** [comment]
Ocaptain from looking at the crash report it still says you're using the out of date java version 1.8.0_51 you may need to look into removing the older version of java or look into the settings of whichever launcher you're using and force it to use the latest java version 1.8.0_241

**Comment by Charismara** [comment]
The twitch launcher uses  his own java installation located in 
`%Twitch_Minecraft_Dir%\Install\runtime `
I guess every user uses that java version

**Comment by Avalonzo** [comment]
> The twitch launcher uses his own java installation located in
> `%Twitch_Minecraft_Dir%\Install\runtime `
> I guess every user uses that java version

Thanks @Charismara I just had a quick look into the Twitch minecraft setting and if you scroll down to launcher and change it from Native to Jar. The Java version which is the next option down let's you change it to the latest Java.
