### ISSUE TITLE
/dank/null/

### ISSUE THREAD

**Issue by HaloBoy12321** [adam9899/Issues#467]
after the 1.3.5.2 update my /dank/null got a render problem with the items in the GUI some are missing and some have the wrong Number displayed. The tool tip is working as expected and extracting wit the Docking station works also as expected .
![javaw_2020-04-15_16-50-12](https://user-images.githubusercontent.com/2693331/79353656-a5391100-7f3b-11ea-8e85-93783e2045e2.png)
![javaw_2020-04-15_16-50-22](https://user-images.githubusercontent.com/2693331/79353803-d9143680-7f3b-11ea-97d7-cbd879d944f8.png)

**Comment by MattFishy18** [comment]
I am in the same boat. I had a small heart attack until I noticed that if I scrolled I still had everything. Would love to know if this can be fixed

**Comment by HeavyDeception** [comment]
Lucky I can help with this. He uploaded a Influx of his mod it was not really ready to be updated to it [as he says here](https://github.com/p455w0rds-MC-Mods/DankNull/issues/278#issuecomment-614873084) so you just need to downgrade. Also just having the name of a mod for the title dose not help on forms like this try adding /Dank/Null Not working.
