### ISSUE TITLE
"Fish Caught"-Quest

### ISSUE THREAD

**Issue by Mirko045** [adam9899/Issues#51]
Hey there,
Just wanted to inform that the "Fish Caught"-quest is not considering any non-vanilla fishes.
So Pam's Harvestcraft fishes, as example aren't calculated to the 5000.

**Comment by adam9899** [comment]
Unfortunately at this moment, the quest will only register vanilla fish as you have outlined. However, I do have plans to eventually add all of the modded fish to the "fish caught" quest pool. Sorry for the disappointment and I hope it doesn't ruin your enjoyment
