### ISSUE TITLE
Player Shop Quest "1M FE" doesn't seem to work

### ISSUE THREAD

**Issue by denehelmbach** [adam9899/Issues#512]
We recently unlocked the Quest "1M FE" by completing every quest in the "Introduction to Science" Chapter, but somehow we can't input Energy into the Task Screen. We already tried several Cables or just putting the Task Screen next to energy producing machines, but nothing happens. Someone knows how to?

**Comment by denehelmbach** [comment]
It seems like the quest wasn't set up correctly because on our Task Screen there is a B like Buckets behind the number. And its actually 10.000.000 and not 1.000.000
![image](https://user-images.githubusercontent.com/57114163/80103031-e2248980-8573-11ea-93d5-d47a0f063532.png)

**Comment by Avalonzo** [comment]
You've selected the wrong quest also there is no 1M FE quest

![image](https://user-images.githubusercontent.com/8142543/80118016-c45d2180-857f-11ea-9a1d-8d0ec633f8ef.png)

**Comment by denehelmbach** [comment]
Yeah you are right, my bad. Thank you
