### ISSUE TITLE
Crash on open inventory

### ISSUE THREAD

**Issue by Chinthor** [adam9899/Issues#532]
Crash report follows. Begins here: java.lang.ArrayIndexOutOfBoundsException
and then seems to blame rendering an Agricraft water channel. But unless something more strange happened, I don't have one on my person or in any chest or storage system. Haven't made any. Could it be crashing because it is rendering something in JEI ? And can some entire mods be disabled from showing in JEI as a temp fix?

https://hastebin.com/hocijezasa.rb
*please wait. technical difficulties.*

**Comment by Avalonzo** [comment]
Please remove the wall of text and copy/paste with https://hastebin.com/ and post the link thank you.

**Comment by Chinthor** [comment]
My bad. Tried and failed to use a spoiler tag. Done

**Comment by Chinthor** [comment]
Tried to use hastebin. 
Got a blank page at the end of that link. 
Went back into the game to get another crash report. 
And it is freaking working. (facepalm)
While I quietly go away, feel free to close this. If it crops up again.... reboot pc?
