### ISSUE TITLE
Major dupe bug

### ISSUE THREAD

**Issue by DreadricW** [adam9899/Issues#540]
You can dupe close to any ore by using the Level Up! Reloaded, by getting the skill that doubles drops when mining ore you can constantly replace the ore and mine it again, works with any ore that has a "overworld" texture. As long as you use silk touch you can do it on diamonds, redstone, lapis and so forth as well as normal ores.

Recommended fix would be to make it so only natural spawned ores would do it and not placed ores if possible.

**Comment by Avalonzo** [comment]
I already reported this back in February #211

**Comment by DreadricW** [comment]
oki
