### ISSUE TITLE
minecraft crash reports

### ISSUE THREAD

**Issue by 2482448** [adam9899/Issues#570]
Minecraft with friends
 While playing with some mods, it suddenly crashed in Minecraft maps. After that, gameplay is impossible.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  ThiccEntities Plugin (thiccentities-1.4 (1).jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0 (1).jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 20. 5. 6 오전 11:13
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at net.minecraft.world.World.func_147448_a(World.java:1949)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2513609440 bytes (2397 MB) / 2857893888 bytes (2725 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xms1G -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version        | Source                                          | Signature                                |
	|:------ |:-------------------- |:-------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2         | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                  | 9.42           | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                  | 8.0.99.99      | forge-1.12.2-14.23.5.2847-universal.jar         | None                                     |
	| LCHIJA | forge                | 14.23.5.2847   | forge-1.12.2-14.23.5.2847-universal.jar         | None                                     |
	| LCHIJA | wumpleutil           | 2.12.9         | wumpleutil-1.12.2-2.12.9.jar                    | None                                     |
	| LCHIJA | foodfunk             | 4.9.6          | foodfunk-1.12.2-4.9.6.jar                       | None                                     |
	| LCHIJA | applecore            | 3.2.0          | AppleCore-mc1.12.2-3.2.0 (1).jar                | None                                     |
	| LCHIJA | backpack             | 3.0.2          | Backpacks-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | bloodmoon            | 1.5.3          | Bloodmoon-MC1.12.2-1.5.3.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | forgelin             | 1.8.3          | Forgelin-1.8.3.jar                              | None                                     |
	| LCHIJA | bountiful            | 2.2.1          | Bountiful-2.2.1 (1).jar                         | None                                     |
	| LCHIJA | codechickenlib       | 3.2.2.353      | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | extendedrenderer     | v1.0           | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCHIJA | coroutil             | 1.12.1-1.2.37  | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCHIJA | configmod            | v1.0           | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCHIJA | crude_start          | 1.0.0          | CrudeStart-1.0.jar                              | None                                     |
	| LCHIJA | customnpcs           | 1.12           | CustomNPCs_1.12.2-(01Oct19).jar                 | None                                     |
	| LCHIJA | death_compass        | 0.0.3          | DeathCompass-0.0.3.jar                          | None                                     |
	| LCHIJA | enderstorage         | 1.0            | EnderStorage-1.12.jar                           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | subcommonlib         | 1.2.0.1        | subcommonlib-sublib-1.12.2-1.2.0.4.jar          | None                                     |
	| LCHIJA | exsartagine          | ${version}     | Exsartagine-1.12.2.jar                          | None                                     |
	| LCHIJA | firstaid             | 1.6.           | firstaid-1.6.6.jar                              | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | grapplemod           | 1.12.2-v11.1   | grapplemod-v11.1-1.12.2.jar                     | None                                     |
	| LCHIJA | ichunutil            | 7.2.2          | iChunUtil-1.12.2-7.2.2.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | lostcities           | 2.0.22         | lostcities-1.12-2.0.22 (1).jar                  | None                                     |
	| LCHIJA | patchouli            | 1.0-20         | Patchouli-1.0-20.jar                            | None                                     |
	| LCHIJA | realistictorches     | 2.1.1          | RealisticTorches-1.12.2-2.1.1.jar               | None                                     |
	| LCHIJA | spiceoflife          | 1.3.12         | SpiceOfLife-mc1.12-1.3.12.jar                   | None                                     |
	| LCHIJA | thiccentities        | GRADLE:VERSION | thiccentities-1.4 (1).jar                       | None                                     |
	| LCHIJA | toolbelt             | 1.7.1          | ToolBelt-1.12.0-1.7.1.jar                       | None                                     |
	| LCHIJA | toughasnails         | 3.1.0.139      | ToughAsNails-1.12.2-3.1.0.139-universal (1).jar | None                                     |
	| LCHIJA | uteamcore            | 2.2.5.147      | u_team_core-1.12.2-2.2.5.147.jar                | None                                     |
	| LCHIJA | universalbestiary    | 1.3.1          | universalbestiary-1.12.2-1.3.1.jar              | None                                     |
	| LCHIJA | variedcommodities    | 1.12.2         | Varied-Commodities-Mod-1.12.2 (1).jar           | None                                     |
	| LCHIJA | zombieawareness      | 1.12.1-1.11.16 | zombieawareness-1.12.1-1.11.16.jar              | None                                     |
	| LCHIJA | immersiveengineering | 0.12-89        | ImmersiveEngineering-0.12-89.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
ThiccEntities Plugin (thiccentities-1.4 (1).jar)
  wiresegal.thicc.asm.ThiccAsmTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0 (1).jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['LuB_eL248'/244, l='world', x=-152.36, y=118.25, z=397.41]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by adam9899** [comment]
It looks like you've added additional mods, this is not something I can help you with unfortunately
