### ISSUE TITLE
LAN playing - Midnight error

### ISSUE THREAD

**Issue by deathbycanon** [adam9899/Issues#58]
when playing in LAN mode the error "the midnight has encountered a problem"  (or something along that line) will continuously spam the game every night.

**Comment by laserlemons** [comment]
The pack author said this is an error caused by Midnight and Vanillafix. For now, the way to get it to stop is to change the rift spawn chance to 0 in the Midnight config. This will stop Midnight's portals from spawning, which are what is causing the error.

**Comment by deathbycanon** [comment]
Awesome, thanks for the reply!
