### ISSUE TITLE
Exploration Bounty issues (mobs not obtainable)

### ISSUE THREAD

**Issue by TherminatorX** [adam9899/Issues#587]
The Dread Knight from Fire and Ice is currently locked in a bedrock-type tomb, with the mob that has the key for it not yet implemented.

The Illusioner from vanilla is completely unobtainable outside of creative mode or commands, as Mojang did not implement it.

Other issues are suspected, as I have yet to find many of the other mobs required after much exploration in their relevant areas, but it could just be RNG.

**Comment by LeDemmers** [comment]
The Charm mod apparently adds Illusioners to roofed forests.
