### ISSUE TITLE
MC Eternal loading error

### ISSUE THREAD

**Issue by doreLynn** [adam9899/Issues#610]
When I try to load the game it gets stuck around tinker's construct. I get the error screen with 2 mods on a list (FoamFix and Tinker's Construct) and the crash report. Here's the link of the report: 

https://pastebin.com/uKPjbWtB
(If I did something wrong, I'm sorry I am new to this- I have a feeling it has something to do with the allocated memory, though)

**Comment by Avalonzo** [comment]
add more ram the modpack needs a minimum of 6gb but 8gb is recommended.
