### ISSUE TITLE
Grass and crops always break under myself while walking.

### ISSUE THREAD

**Issue by gitCodingSenpai** [adam9899/Issues#625]
As my character walks around the grass under me turns to dirt. The crops get upturned, and I have no idea why this is happening. I've taken off all armor, baubles, etc. I cannot come to a solution, so i'm looking for help. Can't find anything online either. If you could lend a hand, would be very appreciated.

**Comment by Avalonzo** [comment]
Sounds like a problem I had I was using a tinkers sword that I had used evil infused ingots for the blade that gave the evil aura modifier. The evil aura modifier can cause what you're describing.

**Comment by gitCodingSenpai** [comment]
Thank you so much it was literally that!
