### ISSUE TITLE
Ice and Fire Dragons Not Dropping Any Scales

### ISSUE THREAD

**Issue by DizzyDJW** [adam9899/Issues#636]
I've killed about 20-50 dragons now, and I've gotten 0 scales from them. I've killed 2 Tier 5 Dragons and still no scales, yet sea serpents and sirens are dropping their scales just fine.
I can't make the dragon forge without scales. Any ideas what's causing this strange bug?

**Comment by dbulm2** [comment]
Have you been right clicking the corpse with an empty hand? You need to manually "harvest" the dragons.

**Comment by DizzyDJW** [comment]
Yes... Haha I get bones and a skull. I'm even able to use an empty bottle on them to gather Ice or Fire Blood but only bones and a skull when using an empty hand, never scales of any kind, even after 50 dragons. I don't know what the deal is.

**Comment by DizzyDJW** [comment]
![2020-05-22_14 52 45](https://user-images.githubusercontent.com/26727521/82700305-f4a9e580-9c3b-11ea-9e92-eb60d08a83ae.png)

My Dragon Skull Collection, just as proof that I've been through many, many dragons and found zero scales.

**Comment by dbulm2** [comment]
You should also be getting flesh (and scales). I can't remember if you can get blood from the skeletons but are you sure they're "fresh"? Does the corpse instantly turn into a skeleton or do you only get bones from the fresh corpses?

**Comment by DizzyDJW** [comment]
When I kill a dragon, it flops to the ground, wings outspread, not yet a skeleton. It will only turn into a skeleton if I use an empty bottle on it or click with an empty hand, but if I choose to forego the bottle, and click the body before it is a skeleton, I don't get anything the first click, then off the skeleton I get bones and a skull.

**Comment by dbulm2** [comment]
It sounds like you're doing everything right. Older dragons obviously drop more stuff but other than that, all I can think of is maybe the configs changed in the latest update? I'm not seeing scales as a setting in mine but if heart is true and you haven't gotten any, I'm out of ideas.
Maybe try some creative testing on stage 5 dragons (if you open a LAN server in singleplayer you can enable cheats) and killing a few.

**Comment by DizzyDJW** [comment]
Well it's working fine now.
I think the issue had to do with attempting to use bottles and empty hands on the dragons, you can only choose one or the other, even if the skin is still there.
