### ISSUE TITLE
Toast Conflict between Actually Additions and Dungeon Tactics.

### ISSUE THREAD

**Issue by ogradyjd** [adam9899/Issues#644]
This is probably a low priority.

In JEI, the recipe for Actually additions toast is one Minecraft bread = 2 Actually Additions toast.

When you put Minecraft bread in a crafting table, however, you get 8 slices of Dungeon Tactics Bread.

Dungeon Tactics "Slice of Bread" isn't ore dictionaried as toast (seems right), so you lose an easy way to double your bread when making Pam's sandwiches.

One Minecraft Bread to 2 Actually Additions Toast
![2020-05-25_9-46-27](https://user-images.githubusercontent.com/4014049/82818497-cb23d080-9e6c-11ea-902b-7f5bd0bf7932.jpg)

One Minecraft Bread to 8 DungeonTactics Slice Of Bread
![2020-05-25_9-47-24](https://user-images.githubusercontent.com/4014049/82818525-d2e37500-9e6c-11ea-81b1-d7208c546086.jpg)

**Comment by dbulm2** [comment]
See the little button with a 2 on it under the recipe output? It's a brilliant little mod that lets you change the output to avoid conflicts. I honestly don't know why it's not in most modpacks.

**Comment by ogradyjd** [comment]
Holy crap. I did not know that.  I'll try it out.  Hopefully it works in AE and Refined Storage.

**EDIT:** Does not work for autocrafting.  This still needs a recipe disambiguation.
