### ISSUE TITLE
Minecraft fails to start

### ISSUE THREAD

**Issue by ReckCJ** [adam9899/Issues#673]
I've uninstalled and reinstalled MC Eternal several times, but any time I attempt to run the pack, it gets halfway through the modloading process and gives an error of "An error during startup prevented Minecraft from starting. The following mod(s) have been identified as potential causes:" and varying the failing mod at random, or sometimes even just saying "unknown". Any ideas as to what I do to fix this?

**Comment by Endbyte** [comment]
How much ram is allocated to the modpack?

**Comment by ReckCJ** [comment]
I think at least 4 GB

**Comment by Endbyte** [comment]
> I think at least 4 GB

How much ram does your system have and please go into twitch settings then minecraft to check how much twitch modpacks use try using 5.5 - 6 gbs of ram if you have that much and see if it starts

**Comment by ogradyjd** [comment]
Take a look at issue #628 

MC Eternal is a kitchen sink pack.  As I've said in other posts, you need a system with at least 16GB to run this pack, giving the pack at least 8 of those 16GB.  Forget what Microsoft says, you have to keep in mind that Windows 10 can take up to 6GB of memory just for the operating system.  If you even glance at the Chrome or Word icons, you lose 2 more GB.  That's 8GB being used just for normal stuff and the operating system.   If you allocate 8GB to MC Eternal, you've just maxed out the memory in your windows system.

Now it gets ugly.  When all the RAM is used up, windows tries to keep everything running by using some of the disk as memory (page swapping).  If you have a regular metal-dust platter HDD (hard-disk drive), that can be thousands of times slower than real RAM, and so everything can slow to a crawl.  In applications, that can work, but with a game and FPS... that does _**not**_ work.  Things are a little better with an SSD (solid-state drive), but still not good enough for acceptable frame rates.

So.  
1. If you have less than 16GB of system RAM - good luck with that.  
1. If you have 16GB, give MC Eternal 8 of those and you might want to close all your browser windows at least, or anything else that uses an appreciable amount of memory or processor.
1. If you have 32GB and up, allocate 10GB to MC Eternal, follow some of the guidelines in #628, and you should have no worries.
