### ISSUE TITLE
Corail Tombstone gone

### ISSUE THREAD

**Issue by Chinthor** [adam9899/Issues#731]
After latest pack update, got warnings about Tombstone features and blocks missing, would not be loaded in current save. Checked the pack and found Corail just missing and unable to add it back cia the Twitch launcher. CurseForge gives a 404 when searching for the mod. I'm only able to find it hosted on sites like 9minecraft.net (blech). Did Corail_31 go missing? Pull all their content? And if you guys saw this coming, is there a new grave mod we will use?

**Comment by adam9899** [comment]
Unfortunately the mod dev acted unprofessionally and had his mod removed from curseforge. The replacement grave being used now is open blocks.

**Comment by Chinthor** [comment]
So bum, much sad. :-(
