### ISSUE TITLE
Cosmetic Armor broken in 1.3.7

### ISSUE THREAD

**Issue by Gravecat** [adam9899/Issues#736]
The CosmeticArmor mod appears to be broken in 1.3.7. The button still appears in the GUI, but pressing it does nothing, and the cosmetic armor that was already equipped in 1.3.6 is no longer visible at all.

Edit: It seems to work fine on a new single-player world, but does not work on a server that was just recently updated from 1.3.6 to 1.3.7.

Edit 2: Looks like the CosmeticArmor mod is missing entirely from the 1.3.7 server pack. Copying the file CosmeticArmorReworked-1.12.2-v4b.jar over to the server's mods folder and restarting the server has fixed it.

**Comment by alexgurrola** [comment]
Thanks!  It turns out FastLeafDecay isn't in the Server Pack as well...

**Comment by Gravecat** [comment]
Looks like it's been re-included and thus fixed in 1.3.7.1 :)
