### ISSUE TITLE
Infinite Gold using Ore Chunks

### ISSUE THREAD

**Issue by MassivxCrafter** [adam9899/Issues#746]
After mining a gold ore there is a chance for it to drop the ore chunks version of the gold, another mod then changes the ore chunks back into gold ore when picked up (Unsure of the mod) You can then replace that ore and have an infinite source of gold. This is being abused on a server I play on and the gold ingots that are gained are being sold to the player shop for infinite shop gold. It appears this only works with gold ore and no other ores.

**Comment by corgiblu** [comment]
This would be a side effect of the instant unify mod.
