### ISSUE TITLE
Bewitchment does not respect oredictionary

### ISSUE THREAD

**Issue by metalpanic** [adam9899/Issues#748]
Several of the Bewitchment rites and recipes do not let you use oredictionary items and will not work without the bewitchment versions. Rite of Greater Cleansing requires bewitchment garlic as well as bewitchment silver and will not accept Pam's garlic or thermal foundation silver. The automatic oredictionary conversion makes activating some of these rites extremely difficult.

**Comment by alexgurrola** [comment]
I'd also note that Bewitchment is greatly out of date.
