### ISSUE TITLE
MC eternal multiplayer server keeps crashing

### ISSUE THREAD

**Issue by stolenkidneys69** [adam9899/Issues#770]
My mc eternal server keeps crashing randomly when people are on it. I have 9GB of ram allocated to the server so I think it might just be a mod compatibility issue but I don't know what to make of the crash report.

[crash-2020-08-04_21.17.09-server (1).txt](https://github.com/adam9899/Issues/files/5039372/crash-2020-08-04_21.17.09-server.1.txt)

**Comment by Yamza** [comment]
Open server properties and set the line that says "max tick" to -1
