### ISSUE TITLE
Moon Boss Summoning Items Unobtainable 

### ISSUE THREAD

**Issue by lynaevm** [adam9899/Issues#780]
I am on version 1.3.7.1 and the moon was first generated in that version.

I have explored extensively.  I have found all of the summoning altars and opened over 160 chests (where I am told the summoning items are found) and have not obtained a single one.  

I was looking through the configs and the only place I can find these items in loot tables are inside a folder labeled "inactive" which makes me worry that these totems are not currently being included in chests.

I did have an early problem where our server admin didn't include the /structures folder and had to go back and add it and reset the moon dimension but since the chests are otherwise full of loot as expected, I don't believe this is related.

Any advice on where else I should be looking or could someone make sure that these items are actually working as intended?

**Comment by adam9899** [comment]
They are all definitely obtainable. I've tested it. Only one of the summoning items is in the generic Moon Loot table, the remaining two are found in specific locations. I'd like to say its just bad luck or you are missing some files.
