### ISSUE TITLE
MC Eternal Server Crash

### ISSUE THREAD

**Issue by zandiamen** [adam9899/Issues#783]
I Have Server allocated ram 12 GB And Its Crashing after playing a while . sometimes every 1 hour and sometimes after 15 minutes and like that. we even reinstalled the mc eternal server pack but still . we don't know if it is a mod that cause this or not even though the server is new so nothing happend in.

note : error changes each jvm crash
crash link : https://pastebin.com/ufPCnHN9

**Comment by kamild1996** [comment]
SIGSEGV errors might mean that your hardware is unstable (especially your CPU and RAM). I'd test system stability with programs like Prime95 or AIDA64 (trial version will do). These are Windows programs though, and I see you're running Linux, maybe someone can recommend similar stress testing programs for Linux as I'm not familiar with those.

**Comment by zandiamen** [comment]
we are running other servers in our panel it is stable 
so that is not our issue

**Comment by kamild1996** [comment]
That doesn't mean it's stable, with other servers running on the same machine you might be constantly running this server in a fragment of memory that's causing you this issue. Additionally, SIGSEGV errors might occur in scenarios so specific that your other MC instances are not causing this error, but something in MC Eternal does. I still insist you should check for hardware instability, incl. memory check with a program like Memtest86.

**Comment by zandiamen** [comment]
> That doesn't mean it's stable, with other servers running on the same machine you might be constantly running this server in a fragment of memory that's causing you this issue. Additionally, SIGSEGV errors might occur in scenarios so specific that your other MC instances are not causing this error, but something in MC Eternal does. I still insist you should check for hardware instability, incl. memory check with a program like Memtest86.

nothing reported with mem test
[5:21 AM]
i dont home-host so hardware errors are unlikely
[5:21 AM]
even if they do exist my host deals with it

**Comment by zandiamen** [comment]
nothing reported with mem test
i dont home-host so hardware errors are unlikely
even if they do exist my host deals with it
