### ISSUE TITLE
Can´t find any laser gun - modpage says there are lasers

### ISSUE THREAD

**Issue by zippoking** [adam9899/Issues#788]
Hi,

so on the curseforge modpage there is this list:
Build a nuclear reactor? Check ✓ Jetpacks? Check ✓ **Lasers? Check** ✓ Create a giant array of high voltage solar panels? Check ✓ Craft a power suit made for pure destruction? Check ✓ Explore space and beyond the stars on a modular rocketship? Check! ✓

I was wondering about the lasers...i dont find any laser gun? The only thing connected is the stone laser from plustic, which is apparently disabled.  What exactly is meant by lasers and how do i get laser guns?

Thanks in advance.
Best regards

**Comment by adam9899** [comment]
Mekanism laser is what is being referenced
