### ISSUE TITLE
Getting debuff mining fatigue, hunger and weakness for ever 

### ISSUE THREAD

**Issue by amysfer** [adam9899/Issues#79]
I got all those debuff mining fatigue, hunger and weakness with 0 on timer so for ever only possibility to get rid of them was to kill myself, potions didn’t work and buckets of milk either. (I can join a clip if necessary)

**Comment by EvanoriMemoria** [comment]
Sounds like radiation poisoning from nuclearcraft. I would suggest crafting some RadAway and finding the source of the radiation (It can spread pretty far from a radioactive wasteland). Not a bug as far as I'm aware, unless there is no radiation source. Crafting a Geiger Counter will allow you to see your radiation levels. Additionally, adding some RadAway to the dungeon loot tables could be an improvement to the modpack. Perhaps even hazmat gear.

**Comment by amysfer** [comment]
Thanks for the info, maybe some tips in chat or something saying it could help cause I had no idea what it could be ^^

**Comment by adam9899** [comment]
NuclearCraft has a chance to spawn a radioactive wasteland biome which causes all of the effects listed above, the settings can be disabled in the NuclearCraft config for players who aren't interested in the mod, or you can move a couple of hundred blocks away. Twitch - Eternal - Settings - Config - NuclearCraft - Radiation

**Comment by amysfer** [comment]
I saw that biome but I didn’t know what was the effect. Maybe you could add some info in the book or tips or a chat text when we got all those effect. I won’t modify anything more fun to see what this can bring. Thanks for the infos !
