### ISSUE TITLE
Multiple Mods Causing Crash?

### ISSUE THREAD

**Issue by ivoryplants** [adam9899/Issues#791]
Everytime I try to launch the pack, it loads perfectly until the end of the first phase of initialization, where it gets hung up on 'Armory Expansion - MatterOverdrive' and 'Ice and Fire.' [Here's the image of the crash result in minecraft](https://prnt.sc/u1s7yw), and [here's the pastebin of the full crash report](https://pastebin.com/cYSZvpeR)
I have about 6GB of ram allocated, am playing MC Eternal 1.3.71, and using the twitch launcher.

**Comment by Joopie-s** [comment]
Yeah i got the same thing, but the cause of error is "unkown" really frustrating, i have used the twitch launcher and also tried it via download but both don't work, its not your RAM cus i have been putting in like 10 gb and still it doesn't work :(
