### ISSUE TITLE
[1.3.7.1] TechReborn Bauxite has no uses

### ISSUE THREAD

**Issue by Rikshy** [adam9899/Issues#793]
RechReborn Bauxite ore spawns naturally but all you can do with it is make dust out of it. the Dust has no use too

**Comment by althritis** [comment]
Use JEI and look for "tiny pile of titanium". The main use for Bauxite is to make Titanium in an electrolyzer a little at a time. You cannot get Titanium Ore or Rutile Ore in the world. This is the only method to get this material.

Have you tested putting bauxite in a smeltery? I'm pretty sure it just turns into aluminum (I haven't tried, but this was a thing in many many packs that had Tinkers + Bauxite).

**Comment by althritis** [comment]
Okay, Bauxite does not smelt like it does in previous patches, but what I said about the Titanium still holds:

![image](https://user-images.githubusercontent.com/22821566/90916569-df616600-e3a6-11ea-9052-10392ae1f71b.png)

**Comment by Rikshy** [comment]
yea I also figured about titanium still wierd it does not smelt into aluminium. In our world Aluminium Ore is quite rare, I have found 3 while getting 3 stacks of bauxite.
