### ISSUE TITLE
repeated lag spikes

### ISSUE THREAD

**Issue by JoePalffy** [adam9899/Issues#807]
After 60-90 minutes of playing i start getting repeated lag spikes for like 2-3 seconds, every 15-20 seconds.
I've only been playing for a few hours, i've built no machines or anything fancy, just 2 crates.
This makes this pack pretty much unplayable for me.

I installed this pack via Twitch yesterday, and i'm playing local offline singleplayer.
I've played other packs recently like Stoneblock 2 using the FTB Launcher, had no lag issues at all.

This screenshot of Task Manager should tell you a few things, like my system specs.
https://photos.app.goo.gl/wsh4hbCWoUecjsjj7

If there is any other info i can provide please let me know, and how i can find what is causing the lagspikes.

Also changing mipmap levels causes the game to freeze up (forever) (tried it twice now)

**Comment by JoePalffy** [comment]
I might have found the issue, i think it didn't have enough memory allocated, even though it's set to automatic, it only had 5.8GB to work with, it would start from 4-4.5GB then it would quickly fill up and then dump 1-1.5GB and that is when the spikes happened.
I set it to use 7.2GB although the F3 screen says it only has 6.4GB, but it's fine now, it's not filling up to 100%.
Although i consider the memory usage growing by 1.5GB and then shrinking back down every 10 seconds to be an issue, that doesn't seem normal, but then again i never look at these things, but at least it's playable now. I'll test it for a few more hours.

**Comment by CrodleMon** [comment]
Another issue i found is terrain animations. Using optifine and tweaking a few settings might also solve you're problem.

**Comment by JoePalffy** [comment]
do you mean particles ? you can turn those off without needing optifine.

Anyway, now with 7.2GB allocated it managed to last 5-6 hours before filling that up too, i have 16GB of ram but with windows, Chrome, Twitch and Minecraft i'm running out, which is funny because the pack maker suggested a "beefy" 8GB machine for optimal performance, but just Java alone was using 8.5GB.
I guess i can't have Chrome open either, then i can give it 2 more gigs.

It's funny i grew up with the 'but can it run Crysis' meme and the 'Minecraft can run on a potato', but modded MC uses more ram then Crysis 3 did.

**Comment by JoePalffy** [comment]
OK, i can confirm that the pack has no more repeated lag spikes with 8GB of memory allocated to it.
There are still plenty of other performance issues, but i think those are common for large packs.
So i guess i'll close this issue.
