### ISSUE TITLE
Sleeping makes me stuck in the bed GUI

### ISSUE THREAD

**Issue by Streambotnt** [adam9899/Issues#857]
Title says basically all, pressing esc does nothing, neither does the "leave bed" button or the /home command (it just teleports me home but the gui is still there).
It runs smoothly if we ignore the fact that whenever I want to shift+leftclick craft stacks of things, like wheat to dough, at first it only crafts one wheat in each stack, and after a few seconds the rest gets converted to dough too. Sorting the inventory via the r-key sometimes behaves odd, sorting the items seemingly random, then sorting it how should have sorted the inventory after a second or two.

**Comment by brisingraerowing** [comment]
The bed thing is a vanilla bug, fixed by VanillaFix (among other mods). The crafting thing is related to how the crafting table looks up the recipe for each craft. Fast Workbench fixes that.

The sorting thing I haven't seen before. Possibly a desync issue.
