### ISSUE TITLE
Some unnecessary and potentially problematic files included with the pack

### ISSUE THREAD

**Issue by katubug** [adam9899/Issues#90]
Hi! I am also a packmaker, and I noticed that there are a few things included with the server pack that probably shouldn't be. Here's a quick list:

- It includes your ops.json, usercache.json, and usernamecache.json. All of those expose your UUID (which admittedly is not a huge deal) but they also mean you're automatically opped on every server that uploads these files.
- The following folders do not need to be included, because they will be automatically generated by the user's server:
-- .mixin.out
-- backups (especially since this contains your backups)
-- journeymap
-- llibrary
-- local
-- logs (especially because this contains your logs)
-- patchouli_books (because you are not shipping any custom books)
-- snapshots-server
-- structures
-- structurize
- The following mods are clientside only and should ideally not be on a server at all (there may be more, these are the ones that specify in the loading logs that they're clientside):
-- AmbientSounds
-- BlockDrops
-- Controlling
-- CustomMainMenu
-- Ding
-- Dynamic Surroundings
-- Enchantment Descriptions
-- Inventory Tweaks
-- Just Enough Resources
-- MenuMobs
-- MineTweakerRecipeMaker (as an aside, if you'd prefer not to use an additional mod for recipe generation, you can use the slightly-less-robust `/ctgui [craftingtable|furnace]` commands that ships with CrT. Also, this mod doesn't need to ship with the client pack to work)
-- MoreOverlays
-- MouseTweaks
-- Overloaded Armor Bar
-- ReAuth
-- ResourceLoader
-- Waila Harvestability
- As a final note regarding the server pack, The Betweenlands offers a special server-only file without all the assets etc to decrease server load times etc.

Personally, I use a batch script I wrote to automatically delete all the clientside mods before I upload. Anyway, hope this helps! Should at least cut your upload time to CF by a bit. :) Thanks for the great pack, have a wonderful day!

**Comment by adam9899** [comment]
Thanks for bringing all of this to my attention I really appreciate it. If I'm honest the server files were thrown together quickly and there is plenty that needs to be done for optimisation, It's just been a time issue for the moment. The next version uploaded will have everything fixed that you've kindly mentioned to me. Glad you've been enjoying the pack! :D

**Comment by katubug** [comment]
No worries, I definitely know how that goes, haha. Thanks for your response! Hope your weekend has been good :D
