### ISSUE TITLE
No Apatite Ore Anywhere

### ISSUE THREAD

**Issue by SylvanusPC** [adam9899/Issues#908]
My friend and I have been playing our MC Eternal world for about a month. We've been having a fun time with the modpack and experiencing no issues, but recently we decided to get into Forestry to make a sugar cane farm, for which of course we need apatite. With this we came to the stunning realization that we have no apatite. We have looked across all the dimensions we currently have access to (midnight, beneath, nether, end, overworld, betweenlands) and we have not found any. JEI says it should be generating at least at the same frequency as diamonds in dimensions like the beneath, but over a dozen quarries later we have none. We can spawn it in if necessary, but I would love to get the apatite legitimately.

Thanks in advance.

**Comment by Joefoe3579** [comment]
Super late to this but apatite has likely been disabled in ore generation. You may be able to enable it in configs so it'll spawn in new chunks. If not, maybe you could use a mystical agriculture seed if you're lucky enough to get some apatite from loot boxes.
