### ISSUE TITLE
Missing Addon ID:293426

### ISSUE THREAD

**Issue by Cal1MeDragon** [adam9899/Issues#926]
I was trying to install MC Eternal and curseforge popup advised of a missing addon and wont let me install any help is appreciated.

**Comment by Dragonspun** [comment]
I have also been getting this issue just today. I recently deleted the old install that I had customized some configs in and was trying to install a fresh, non-altered version, but get this same issue. 
After multiple tries, I have realized it keeps stopping at different mods each time. 

Update: After many, *many* tries, I finally got it to install. Try again, OP.
