### ISSUE TITLE
Astral Sorcery with Shaders

### ISSUE THREAD

**Issue by NonEssentialCelestial** [adam9899/Issues#928]
I wanted to play Mc Eternal Lite with shaders but Astral Sorcery causes
![Ekran görüntüsü 2021-01-18 003656](https://user-images.githubusercontent.com/77590936/104857290-5e43d600-5928-11eb-99c7-f7801c037c34.png)
 this visual glitch.
I've seen people saying adding 0 to this line fixes it 
![Ekran görüntüsü 2021-01-18 004243](https://user-images.githubusercontent.com/77590936/104856914-2176df80-5926-11eb-81de-72e4b5f70219.png)
But it didnt fix it for me. It looks like this ingame config of astral sorcery
![Ekran görüntüsü 2021-01-18 003617](https://user-images.githubusercontent.com/77590936/104856922-33588280-5926-11eb-930d-37c19800c230.png)
Is there a any another way to fix this?

Java is updated to last version, using correct version of optifine. And im using DocteurDreads Shaders v02 - Medium for shader pack

**Comment by reddvilzz** [comment]
Have you read the discord tips?

Here I quote it for you, there are some other mods that use shaders for the sky outside astral sorcery

> MC Eternal has so many mods that cause issues if you want to use Complementary Shaders that is based on BSL, but here are the fixes most, if not all of them:
- Astral Sorcery mod: Open the mod config file, set "S:weakSkyRenders" to "0". (Should look like this.)
- Advanced Rocketry mod: Open the mod config file, set "B:overworldSkyOverride" to "false".
- Botania mod: Open the mod config file, set "B:fancySkybox.enable" AND "B:shaders.enabled" to "false".
- Thermal Dynamics mod: Add this mod to your modpack. ** https://www.curseforge.com/minecraft/mc-mods/unifine
- The Midnight mod: Open the mod config file, set "B:rift_shaders" to "false".
- Rats mod: Go to Video Settings > Performance, and set "Fast Render" to OFF.
- TheBetweenlands config file under rendering I have B:dimension_shader_only=false and   B:use_shader=false (the last one is true by default) and when you touch the portal the image freezes (but the game keeps running)

**Comment by NonEssentialCelestial** [comment]
> Have you read the discord tips?
> 
> Here I quote it for you, there are some other mods that use shaders for the sky outside astral sorcery
> 
> > MC Eternal has so many mods that cause issues if you want to use Complementary Shaders that is based on BSL, but here are the fixes most, if not all of them:
> 
> * Astral Sorcery mod: Open the mod config file, set "S:weakSkyRenders" to "0". (Should look like this.)
> * Advanced Rocketry mod: Open the mod config file, set "B:overworldSkyOverride" to "false".
> * Botania mod: Open the mod config file, set "B:fancySkybox.enable" AND "B:shaders.enabled" to "false".
> * Thermal Dynamics mod: Add this mod to your modpack. ** https://www.curseforge.com/minecraft/mc-mods/unifine
> * The Midnight mod: Open the mod config file, set "B:rift_shaders" to "false".
> * Rats mod: Go to Video Settings > Performance, and set "Fast Render" to OFF.
> * TheBetweenlands config file under rendering I have B:dimension_shader_only=false and   B:use_shader=false (the last one is true by default) and when you touch the portal the image freezes (but the game keeps running)

Doing these worked thank you very much!
